#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from std_msgs.msg import String

from voicetext import VoiceText


def callback(data):
    vt.speak(data.data)


if __name__ == '__main__':
    rospy.init_node('voicetext')
    user_name = rospy.get_param('~user_name')
    password = rospy.get_param('~password', '')
    speaker = rospy.get_param('~speaker', 'hikari')

    vt = VoiceText(user_name=user_name, password=password, speaker=speaker)
    rospy.Subscriber("speech", String, callback)
    rospy.spin()
